name: First Workflow
on: 
  workflow_dispatch:
  push:  # Event that will trigger this workflow, this one requires user to manually start the workflow
jobs: 
 first-job:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Print greeting
       run: echo "Hello world"
     - name: Print goodbye
       run: |  # Pipe allows to run multiple shell commands
         echo "Goodbye"
         echo "Goodbye again"
