name: First Workflow
on: workflow_dispatch # Event that will trigger this workflow, this one requires user to manually start the workflow
jobs: 
 first-job:
   runs-on: ubuntu-latest
   steps: 
     - name: Print greeting
       run: echo "Hello world"
     - name: Print goodbye
       run: |  # Pipe allows to run multiple shell commands
         echo "Goodbye"
         echo "Goodbye again"
